WIP

diff --git a/scripts/ip b/scripts/ip
--- a/scripts/ip
+++ b/scripts/ip
@@ -32,13 +32,14 @@ ip::find() {
 		return
 	fi
 
-	if [[ -z "$TAILNET_NAME" ]]; then
-		echo "TAILNET_NAME is not set" >&2
+	local tailnetName="$TF_VAR_tailnet_name"
+	if [[ -z "$tailnetName" ]]; then
+		echo "Missing Terraform variable: tailnet_name" >&2
 		return 1
 	fi
 
-	if getent hosts "$name.$TAILNET_NAME.ts.net" > /dev/null; then
-		echo "$name.$TAILNET_NAME.ts.net"
+	if getent hosts "$name.$tailnetName.ts.net" > /dev/null; then
+		echo "$name.$tailnetName.ts.net"
 		return
 	fi
 
